**Zestaw 4:**

**Zad 1:**

In [ ]:
import tensorflow as tf

In [ ]:
A = tf.constant([[2.0, -3.0, 1.0], [4.0, 5.0, 0.0], [2.0, -1.0, 3.0]], dtype=tf.float32)
B = tf.constant([3.0, -4.0, -2.0], dtype=tf.float64) # z określeniem typu 
C = tf.constant([[2, 4], [-2, 1], [5, 0]], dtype=tf.int32) # z określeniem typu 
D = tf.constant([[2], [6], [8]]) # z określeniem typu 
print(A, "\n")
print(B, "\n")
print(C, "\n")
print(D, "\n")

tf.Tensor(
[[ 2. -3.  1.]
 [ 4.  5.  0.]
 [ 2. -1.  3.]], shape=(3, 3), dtype=float32) 

tf.Tensor([ 3. -4. -2.], shape=(3,), dtype=float64) 

tf.Tensor(
[[ 2  4]
 [-2  1]
 [ 5  0]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[2]
 [6]
 [8]], shape=(3, 1), dtype=int32) 



In [ ]:
print(A.shape)
print(B.shape)
print(C.shape)

(3, 3)
(3,)
(3, 2)


In [ ]:
print(A.dtype)
print(B.dtype)
print(C.dtype)

<dtype: 'float32'>
<dtype: 'float64'>
<dtype: 'int32'>


In [ ]:
A_prim = tf.cast(A,tf.int32)
print(A_prim.dtype)

<dtype: 'int32'>


Operacja tf.matmul możliwa jest dla tensorów, które spełniają 2 warunki:

a) ich wymiary wewnętrzne się zgadzają (ilośc kolumn pierwszego tensora = ilość wierszy drugiego tensora)

b) ich typy są zgodne (gdy nie podajemy typu, to dla liczb całkowitych domyślny typ to int32)

In [ ]:
w1 = tf.matmul(A_prim,D)
w1

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[-6],
       [38],
       [22]], dtype=int32)>

In [ ]:
w2 = tf.matmul(A,A)
w2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ -6., -22.,   5.],
       [ 28.,  13.,   4.],
       [  6., -14.,  11.]], dtype=float32)>

In [ ]:
w3 = tf.matmul(A_prim, C)
w3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15,  5],
       [-2, 21],
       [21,  7]], dtype=int32)>

In [ ]:
w4 = tf.matmul(A_prim, D)
w4

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[-6],
       [38],
       [22]], dtype=int32)>

================================================================================

In [ ]:
w5 = tf.multiply(A,A)
w5

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 4.,  9.,  1.],
       [16., 25.,  0.],
       [ 4.,  1.,  9.]], dtype=float32)>

In [ ]:
w6 = tf.multiply(B,B)
w6

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 9., 16.,  4.])>

In [ ]:
w7 = tf.multiply(C,C)
w7

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 16],
       [ 4,  1],
       [25,  0]], dtype=int32)>

In [ ]:
w8 = tf.multiply(C, D)
w8

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  4,   8],
       [-12,   6],
       [ 40,   0]], dtype=int32)>

In [ ]:
w9 = tf.multiply(D, C)
w9

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  4,   8],
       [-12,   6],
       [ 40,   0]], dtype=int32)>

In [ ]:
w10 = tf.multiply(D, D)
w10

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 4],
       [36],
       [64]], dtype=int32)>

================================================================================

In [ ]:
w11 = tf.add(A,A)
w11

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 4., -6.,  2.],
       [ 8., 10.,  0.],
       [ 4., -2.,  6.]], dtype=float32)>

In [ ]:
w12 = tf.add(B,B)
w12

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 6., -8., -4.])>

In [ ]:
w13 = tf.add(C,C)
w13

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  8],
       [-4,  2],
       [10,  0]], dtype=int32)>

In [ ]:
w14 = tf.add(C,D)
w14

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 4,  7],
       [13,  8]], dtype=int32)>

In [ ]:
w15 = tf.add(D, C)
w15

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 4,  7],
       [13,  8]], dtype=int32)>

In [ ]:
w16 = tf.add(D, D)
w16

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 4],
       [12],
       [16]], dtype=int32)>

**Zad 2:**

In [ ]:
p = tf.Variable(0)
for i in range(0, 9, 1):
  p.assign_add(5)
  print(p.numpy())

5
10
15
20
25
30
35
40
45


**Zad 3:**

In [ ]:
t = tf.constant([1, -3, 4, 6, 10, -12, 34, 7, 10, 8])
suma = tf.Variable(0)

for i in range (0, tf.size(t).numpy(), 1):
  suma.assign_add(t[i]*t[i]) 

suma.numpy()

1675

**Zad 4:**

In [ ]:
A_prim = tf.Variable([[2.0, -3.0, 1.0], [4.0, 5.0, 0.0], [2.0, -1.0, 3.0]], dtype=tf.float32)
tab = tf.Variable([[100.0, 100.0, 100.0], [100.0, 100.0, 100.0], [100.0, 100.0, 100.0]])
A_prim.assign_sub(tab)
print(A_prim.numpy())

print(A_prim.dtype)
print(tab.dtype)




[[ -98. -103.  -99.]
 [ -96.  -95. -100.]
 [ -98. -101.  -97.]]
<dtype: 'float32'>
<dtype: 'float32'>


**Tak, można dla tensora A z pierwszego zadania wykonać operację assign_sub, ale tylko wtedy, gdy jako jej argument podamy tensor o identycznych wymiarach jak tensor A (czyli w tym wypadku [3,3]).**

**Muszą również zgadzać się typy tensorów, jednak gdy zadeklarujemy tensor tab bez podania typu, to domyślnie dla wartości zmiennoprzecinkowych będzie to float32, a więc w tym wypadku odpowiada on typowi macierzy A_prim**